{
	"version": 1574138169,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/lrboarders-sheet0.png",
		"images/sub-sheet0.png",
		"images/fishornage-sheet0.png",
		"images/appron2-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/dagerleft-sheet0.png",
		"images/dagerright-sheet0.png",
		"images/amaretto-sheet0.png",
		"images/winner-sheet0.png",
		"images/dolphin-sheet0.png",
		"images/submit-sheet0.png",
		"images/background-sheet0.png",
		"images/scorebackground-sheet0.png",
		"images/startbackground.png",
		"images/winnerbackground.png",
		"images/helpsoundoffpic-sheet0.png",
		"images/helpsoundonpic-sheet0.png",
		"images/fruitbowl2-sheet0.png",
		"images/player3-sheet0.png",
		"images/flooroflevel.png",
		"images/sprite-sheet0.png",
		"images/starfish-sheet0.png",
		"images/jump-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/pausebutton-sheet0.png",
		"images/block.png",
		"images/apple2-sheet0.png",
		"images/fishorange-sheet0.png",
		"images/setapple-sheet0.png",
		"images/dolphin2-sheet0.png",
		"images/sub2-sheet0.png",
		"images/leftbar-sheet0.png",
		"images/level1back-sheet0.png",
		"images/getready-sheet0.png",
		"images/dolphinicon-sheet0.png",
		"images/spritefont.png",
		"images/level2splash-sheet0.png",
		"images/bonusscreen-sheet0.png",
		"images/level1splash-sheet0.png",
		"images/thumblife-sheet0.png",
		"images/level3back-sheet0.png",
		"images/starfishicon-sheet0.png",
		"images/level3start-sheet0.png",
		"images/level3splash-sheet0.png",
		"images/soundoff-sheet0.png",
		"images/soundon-sheet0.png",
		"images/apple-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite3-sheet0.png",
		"media/gameoverfinal.m4a",
		"media/gameoverfinal.ogg",
		"media/extra life.m4a",
		"media/extra life.ogg",
		"media/caplaugh1.m4a",
		"media/caplaugh1.ogg",
		"media/everything.m4a",
		"media/everything.ogg",
		"media/butchers appron.m4a",
		"media/butchers appron.ogg",
		"media/starfish.m4a",
		"media/starfish.ogg",
		"media/drunken sailor music.m4a",
		"media/drunken sailor music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"loading-logo.png",
		"icon-256.png"
	]
}